### ISSUE TITLE
setup extensions 

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/citywide-jupyterhub#14]
* [x] NBDime
* [x] ipyleaflet
* [x] Jupyterlab-git - or jupyterlab-github or both. @ian-r-rose thoughts? 
* [x] jupyterlab-sql
* [x] [Jupyterlab-dash](https://github.com/plotly/jupyterlab-dash)
* [x] jupyterlab-bokeh
* [x] [Jupyterlab-spreadsheet](https://github.com/quigleyj97/jupyterlab-spreadsheet)
* [ ] more TK!

**Comment by ian-r-rose** [comment]
A few notes on this:
1. nbdime is a priority. Hasn't been released for 1.0 yet, but as soon as it is (probably within the next few days) I'll add it.
2. ipyleaflet -- good idea
3. Probably both jupyterlab-git and jupyterlab-github are useful. jupyterlab-github won't be fully useful until I figure out how to pass the github oauth token from the user login to the environment
4. jupyterlab-sql is cool, and a good idea.
5. Sure.
6. Sure.
7. jupyterlab-spreadsheet is cool, and Joe knows what he is doing.

A few more:
1. dask-labextension is one of mine and pretty useful, I think.
2. The GeoJSON viewer is quite useful, though if you open too large of a GeoJSON file it can cause the browser to hang.
3. The table-of-contents extension is also pretty useful

**Comment by hunterowens** [comment]
I'm attempting to work on a PR for jupyterlab-dash today, but if I don't get something in @ian-r-rose can you take a look?

**Comment by ian-r-rose** [comment]
Dash and Excel support in #21

**Comment by ian-r-rose** [comment]
Git and GitHub support in #22

**Comment by hunterowens** [comment]
with #24 done, I think we can close this issue for now. @ian-r-rose ?

**Comment by ian-r-rose** [comment]
Yep!
