### ISSUE TITLE
Install PgAdmin

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/citywide-jupyterhub#25]
PgAdmin4 is a real pain to get installed right now, but if it gets simpler, it should be possible to include it in the docker image, and proxy the web app to the user.

**Comment by hunterowens** [comment]
related, @thekaveman did a pgAdmin image as part of [mds-provider-services](https://github.com/CityofSantaMonica/mds-provider-services/tree/master/client)

**Comment by ian-r-rose** [comment]
Yeah, it would be great to figure out if we could orchestrate other containers (like the pgadmin image) with our own image, but I suspect that would be difficult with the current helm chart.

I looked into installing the pgadmin web server locally into our image, and it is also really challenging -- it doesn't really like operating in a user environment with reduced permissions, and the install story is pretty bad at the moment.

One person who figured it out with a bunch of hoop-jumping is [here](https://github.com/psychemedia/jupyter-postgres-demo/tree/pgadmin).

Another cool option is [Franchise](https://franchise.cloud/).

**Comment by hunterowens** [comment]
I'd be happy to go with Franchise, rather than PGAdmin.
