### ISSUE TITLE
Intake 0.5.2 has error with reading mirroed geojson on S3

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/citywide-jupyterhub#32]
error: `TypeError: __init__() got an unexpected keyword argument 'storage_options'` 

resolution: pin intake to 0.5.1?

**Comment by tiffanychu90** [comment]
additional error happened with dask 0.2.2 and intake.

**Comment by ian-r-rose** [comment]
Yeah, I think you are right.

**Comment by hunterowens** [comment]
Let's discuss this issue today at code review

**Comment by ian-r-rose** [comment]
Good news, Martin has a fix for this in intake, which should be available in the next release. I'll pin to 0.5.1 until then.

**Comment by ian-r-rose** [comment]
Aand, the fixed has been merged.
