### ISSUE TITLE
write setup / getting started guide

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/citywide-jupyterhub#4]
* [ ]  setup AWS / similar credentials 
* [ ] clone  / push git repos 
* [ ] others, tbd

**Comment by ian-r-rose** [comment]
Work on this has begun, if you think of information we should add, please submit a PR to [this](./cityofla-labextension/welcome.md) markdown file,

**Comment by ian-r-rose** [comment]
I think this is more-or-less done in #33, #28, 78f56f87d33b7a45a30acd372d731284c3b012d8. We can open new issues with more specific onboarding needs as they arise.
