### ISSUE TITLE
Pull Requests?

### ISSUE THREAD

**Issue by brendanbailey** [CityOfLosAngeles/citywide-jupyterhub#42]
How would you like pull requests to be done? Would you rather that we clone and create our own branch or fork the repository?

With cloning and creating my own branch, I ran into a permissioning issue:
```git push --set-upstream origin nlp-libraries
ERROR: Permission to CityOfLosAngeles/citywide-jupyterhub.git denied to brendanbailey.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

With forking, it makes the repo public. I'm not sure if that is something you want at this point.

**Comment by ian-r-rose** [comment]
This is already a public repo, so feel free to fork and keep in a public account @brendanbailey. I've also added you as a collaborator, so you should be able to create branches here as well.

**Comment by brendanbailey** [comment]
Great - thanks!
