### ISSUE TITLE
jupyter-notify

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/citywide-jupyterhub#50]
[because some of us have long running tasks and too many tabs](https://github.com/ShopRunner/jupyter-notify) 

include in spawner args

**Comment by ian-r-rose** [comment]
Looks like this doesn't yet support JupyterLab.

**Comment by hunterowens** [comment]
whomp. Will close for now and ping @mdagost

**Comment by mdagost** [comment]
I'd love a PR!  Some people have gotten it to work with JupyterLab: https://github.com/ShopRunner/jupyter-notify/issues/33
