### ISSUE TITLE
cx_Oracle 

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/citywide-jupyterhub#54]

**Comment by hunterowens** [comment]
[guide to install cx_Oracle on Ubuntu](https://gist.github.com/kimus/10012910)

**Comment by ian-r-rose** [comment]
That guide is horrific. Oracle really doesn't want anyone using anything other than Oracle Linux, do they?

**Comment by hunterowens** [comment]
at least according to the [oracle dockerfiles](https://github.com/oracle/docker-images)

**Comment by hunterowens** [comment]
[here's an ubuntu image dockerfile](https://github.com/brmzkw/cx_oracle/blob/master/Dockerfile) that we might want to crib from

**Comment by ian-r-rose** [comment]
Looks like it's the same maintainer as `cx_Oracle`, so at least it seems legit.

**Comment by ian-r-rose** [comment]
@hunterowens Do you have access to any oracle databases that we might be able to test on?
