### ISSUE TITLE
Add censusdata

### ISSUE THREAD

**Issue by tiffanychu90** [CityOfLosAngeles/citywide-jupyterhub#67]
* Python package for downloading Census data through Census API
[PyPI](https://pypi.org/project/CensusData/)

**Comment by ian-r-rose** [comment]
@tiffanychu90 we discussed this briefly a few weeks ago, and at the time thought that `census-data-downloader` was a better-supported option for the same task. That should already be live, as of #64. Is that package not good enough for your needs?

**Comment by ian-r-rose** [comment]
Fixed by #72
